# Generated by Django 4.2.2 on 2023-06-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_by', models.ManyToManyField(to='my_app.hashtag')),
            ],
        ),
    ]
